In [7]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

# Solution 1
# Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

# Yes there is a difference in the data type of both the

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [11]:
# Solution 2

# Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [12]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [14]:

# Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.

for i in list_:
    print(type(i))
    
for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [16]:
# Consider the below code to answer further questions:
    
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# Solution 4

# Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

num_array.shape

(2, 3)

In [17]:
num_array.size

6

In [21]:
# Solution 5

# Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.

list_1 = [[0,0,0], [0,0,0], [0,0,0]]

zero_matrix = np.array(list_1)
print(type(zero_matrix))
print(zero_matrix)

<class 'numpy.ndarray'>
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [23]:
# Solution 6

# Create an identity matrix of shape (5,5) using numpy functions?

identity_matrix = np.identity(5, dtype = 'int')
identity_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])